CREATE TABLE usuarios(
    id BIGINT AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    perfil TINYINT NOT NULL,
    activo BIT NOT NULL DEFAULT 1,
    PRIMARY KEY(id)
)CHARACTER SET utf8mb4;