CREATE TABLE topicos(
    id BIGINT AUTO_INCREMENT NOT NULL,
    titulo VARCHAR(255) UNIQUE NOT NULL,
    mensaje VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    usuario_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);