CREATE TABLE respuestas(
    id BIGINT AUTO_INCREMENT NOT NULL,
    mensaje TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
    topico_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_id BIGINT NOT NULL,
    solucion BIT NOT NULL DEFAULT 0,
    actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
)CHARACTER SET utf8mb4;
