INSERT INTO usuarios(nombre, email, contrasena, perfil) VALUES
('Darwin Mireles','darwin.mireles@correo.net','$2a$12$de32S/J2SwZ8acpnmuMjzeDbJyKMvfcfeZOL2CJNgI.oQJ/EcWFpe',1),
('Darrin Berryann','iwathall41@reverbnation.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',4),
('Davy Kellough','gkibbeyo@vkontakte.ru','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Carter Estick','gbeston6d@ebeden.co.uk','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Ajay Doyle','lsorey1t@webeden.co.uk','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Cirilo Menzies','nbexley6g@mayoclinic.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Herb Worviell','wmacdowal49@wikia.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Imogene Chavey','ekaygill6q@dropbox.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Florida Kiddey','vkubach6t@smh.com.au','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Tom Egdale','crubery6s@simplemachines.org','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Erhart Abdee','jvenneur60@bbb.org','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Neda Feore','mguyi@imdb.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Eugene Egdale','lstovine51@irs.gov','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',3),
('Cammie De Robertis','hwilber2t@blinklist.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',3),
('Doretta Keitley','kcathro68@unicef.org','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Way Abdee','wmacdowal49@unicef.org','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Gilemette Whitsey','sberryann4q@ebay.co.uk','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Willey Fraschetti','ghaighton4t@hhs.gov','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Brewer Bergeon','cmeddows1q@aboutads.info','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Cosette Kibbey','nolfert4o@pbs.org','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Desdemona Sleite','astoppard26@desdev.cn','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Sondra Ludron','abarrick4b@deviantart.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Carola Loache','jcorssenf@independent.co.uk','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Jilly Bohey','fradleigh22@shop-pro.jp','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Shelton Kubach','hwarbrick1s@alibaba.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Desdemona Cassell','vhandrik5z@adobe.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Adrien Brabham','ecraiker58@mapy.cz','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Renata Lauks','gfraschetti54@independent.co.uk','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Sheeree Esposi','hmanketell1n@cbslocal.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Tom Godmar','jcorssenf@dyndns.org','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Mickie Sorey','gbeston6d@businessweek.com','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Ettie Spellissy','amelley65@rambler.ru','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Niccolo Anten','cwindrum31@nsw.gov.au','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',2),
('Smith Rubery','kaitkeny@telegraph.co.uk','$2a$10$.7lCGAuBjURDmRVbdVSQLeEnaIsSWOQEzebFmsiO3P8Wfz8isQ0KS',1);


INSERT INTO cursos(nombre, categoria) VALUES
('Bienvenida', 'DESARROLLO_PERSONAL'),
('Estructura de datos', 'PROGRAMACION'),
('Introducción a JavaScript', 'FRONTEND'),
('HTML y CCS Desde Cero', 'FRONTEND'),
('Programación Orientada a Objetos POO', 'PROGRAMACION'),
('Git y GitHub', 'PROGRAMACION'),
('Aprenda React desde cero', 'FRONTEND'),
('Demanda del mercado', 'DESARROLLO_PERSONAL'),
('Spring Boot', 'BACKEND'),
('Spring Boot y JPA', 'BACKEND'),
('Desarrollar una API Rest en Java', 'BACKEND'),
('Bases de Datos', 'BACKEND'),
('Persistencia de datos', 'BACKEND'),
('Portafolio como carta de presentación', 'DESARROLLO_PERSONAL'),
('Spring Security', 'BACKEND'),
('Fundamentos de Agilidad', 'DESARROLLO_PERSONAL');

INSERT INTO topicos(titulo,mensaje,usuario_id,curso_id) VALUES
('BIENVENIDA','Sean todos bienvenidos a este Foro, acá podrán despejar todas sus dudas',1,1),
('PRESENTACIÓN','En este espacio pueden presentarse, y comentar algunos detalles sobre ustedes mismos',2,1),
('No puedo instalar Postgres', 'El instalador muestra el error 0x456', 12, 12),
('Error conectando a la base de Datos','Tengo problemas para conectar la base de datos, el error es: #1046 - No database selected;',10,12),
('Error conectando a la BD','Tengo problemas para conectar la base de datos, el error es: #1046 - No database selected;',5,12),
('Consulta MySQL', '¿Alguno de ustedes sabe como crear una relación entre las tablas de MySQL?',12,12),
('Visor de Base de Datos','Chicos, ¿Qué administradores de base de datos estan usando ustedes?',7,12),
('POO', 'No entiendo la sobrecarga de los metodos, que es eso ?',8,5),
('JPA y Persistencia','Ayuda!!!, mi app no está guardando nada en la base de datos',15,10),
('Error con FlyWay','Tengo problemas para evitar errores en el inicio de la aplicación debidos a las migraciones de Flyway',15,12);

INSERT INTO respuestas(mensaje,topico_id,usuario_id,solucion) VALUES
('Gracias, estoy muy emocionado por participar al maximo en este programa !!!',1,21,false),
('Siiiii.... estamos aqui, que empiece la programación, Gracias Oracle, Gracias Alura Latan',1,18,false),
('Hola! soy Juan Lugo y me gustan los gatos, la programación y el anime',2,12,false),
('Hola a tod@s, espero que nos conozcamos, soy de Paraguay ay ay Paraguay',2,15,false),
('Intenta instalarlo con privilegios de administrador',3,5,false),
('Solo tienes que descargar el paquete desde la pagina oficial https://www.postgresql.org/download/',3,4,true),
('Ya probaste si el servidor esta activo?',4,7,false),
('Debes crear la base de Datos primero!',4,9,true),
('Este tópico esta repetido, puedes encontrar la solución en el topico id: 4',5,10,true),
('Puedes revisar la documentación oficial en la pagina web, alli están todas los tipos de relaciones',6,14,false),
('A mi tambien me está pasando lo mismo, alguno sabe la solución?',6,19,false),
('Hola hay alguien ahi...?',6,19,false),
('La solución está en el primer mensaje',6,2,true),
('Yo uso PgAdmin para Postgres',7,1,false),
('A mi me gusta Workbench para Mysql',7,3,false),
('Yo estoy usando Navicat Premium, hay varios crack en internet, y puedes abrir cualquier tipo de base de datos',7,2,false),
('Si Navicat es buenisimo, pero consume mucho recursos y a veces se cuelga, yo soy de la vieja escuela y uso Heidy =)',7,1,true),
('Lo mejor es que repases los conceptos de POO antes de continuar',8,1,false),
('Bueno es cuando creas uel mismo metodo o constructor pero con diferente numero de parametros, creo!',8,18,false),
('Yo tengo el mismo problema, alguno nos puede ayudar?',10,16,false);