INSERT INTO usuarios(nombre, email, contrasena, perfil) VALUES
('Piper Roddie','mcassell7@japanpost.jp','Siddons',1),
('Darrin Berryann','iwathall41@reverbnation.com','Kaygill',4),
('Davy Kellough','gkibbeyo@vkontakte.ru','Neles',2),
('Carter Estick','gbeston6d@ebeden.co.uk','Docherty',2),
('Ajay Doyle','lsorey1t@webeden.co.uk','Pycock',2),
('Cirilo Menzies','nbexley6g@mayoclinic.com','Guy',2),
('Herb Worviell','wmacdowal49@wikia.com','Halward',2),
('Imogene Chavey','ekaygill6q@dropbox.com','Harriott',2),
('Florida Kiddey','vkubach6t@smh.com.au','Wilber',2),
('Tom Egdale','crubery6s@simplemachines.org','Corssen',2),
('Erhart Abdee','jvenneur60@bbb.org','Vlasyuk',2),
('Neda Feore','mguyi@imdb.com','Hamsley',2),
('Eugene Egdale','lstovine51@irs.gov','Hamsley',3),
('Cammie De Robertis','hwilber2t@blinklist.com','Bonass',3),
('Doretta Keitley','kcathro68@unicef.org','Bartel',2),
('Way Abdee','wmacdowal49@unicef.org','Aery',2),
('Gilemette Whitsey','sberryann4q@ebay.co.uk','Cunliffe',2),
('Willey Fraschetti','ghaighton4t@hhs.gov','Codner',2),
('Brewer Bergeon','cmeddows1q@aboutads.info','Martinon',2),
('Cosette Kibbey','nolfert4o@pbs.org','Trousdale',2),
('Desdemona Sleite','astoppard26@desdev.cn','Kaygill',2),
('Sondra Ludron','abarrick4b@deviantart.com','Helgass',2),
('Carola Loache','jcorssenf@independent.co.uk','Keitley',2),
('Jilly Bohey','fradleigh22@shop-pro.jp','Gecks',2),
('Shelton Kubach','hwarbrick1s@alibaba.com','Hucklesby',2),
('Desdemona Cassell','vhandrik5z@adobe.com','Lemerie',2),
('Adrien Brabham','ecraiker58@mapy.cz','MacCafferky',2),
('Renata Lauks','gfraschetti54@independent.co.uk','Ference',2),
('Sheeree Esposi','hmanketell1n@cbslocal.com','Trousdale',2),
('Tom Godmar','jcorssenf@dyndns.org','Archer',2),
('Mickie Sorey','gbeston6d@businessweek.com','Malinson',2),
('Ettie Spellissy','amelley65@rambler.ru','Cameli',2),
('Niccolo Anten','cwindrum31@nsw.gov.au','Haighton',2),
('Smith Rubery','kaitkeny@telegraph.co.uk','Oliver',1);

INSERT INTO cursos(nombre, categoria) VALUES
('Bienvenida', 'DESARROLLO_PERSONAL'),
('Estructura de datos', 'PROGRAMACION'),
('Introducción a JavaScript', 'FRONTEND'),
('HTML y CCS Desde Cero', 'FRONTEND'),
('Programación Orientada a Objetos POO', 'PROGRAMACION'),
('Git y GitHub', 'PROGRAMACION'),
('Aprenda React desde cero', 'FRONTEND'),
('Demanda del mercado', 'DESARROLLO_PERSONAL'),
('Spring Boot', 'BACKEND'),
('Spring Boot y JPA', 'BACKEND'),
('Desarrollar una API Rest en Java', 'BACKEND'),
('Bases de Datos', 'BACKEND'),
('Persistencia de datos', 'BACKEND'),
('Portafolio como carta de presentación', 'DESARROLLO_PERSONAL'),
('Spring Security', 'BACKEND'),
('Fundamentos de Agilidad', 'DESARROLLO_PERSONAL');

INSERT INTO topicos(titulo,mensaje,usuario_id,curso_id) VALUES
('BIENVENIDA','Sean todos bienvenidos a este Foro, acá podrán despejar todas sus dudas',1,1),
('PRESENTACIÓN','En este espacio pueden presentarse, y comentar algunos detalles sobre ustedes mismos',2,1),
('No puedo instalar Postgres', 'El instalador muestra el error 0x456', 12, 12),
('Error conectando a la base de Datos','Tengo problemas para conectar la base de datos, el error es: #1046 - No database selected;',10,12),
('Error conectando a la BD','Tengo problemas para conectar la base de datos, el error es: #1046 - No database selected;',5,12),
('Consulta MySQL', '¿Alguno de ustedes sabe como crear una relación entre las tablas de MySQL?',12,12),
('Visor de Base de Datos','Chicos, ¿Qué administradores de base de datos estan usando ustedes?',7,12),
('POO', 'No entiendo la sobrecarga de los metodos, que es eso ?',8,5),
('Error con FlyWay','Tengo problemas para evitar errores en el inicio de la aplicación debidos a las migraciones de Flyway',15,12);
